### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by w-vi** [apiaryio/black-belt#115]
Is python 3.x supported or not, README says nothing about it and on py35 it doesn't work.

**Comment by honzajavorek** [comment]
Well, it was created by @Almad, whose relationship to Python 3 is something like

![py3](http://cdn.meme.am/instances/53105542.jpg)

It's 2.7 at most and it's not going to be 3 until someone ports it. Nobody will port it, because it has no tests.

**Comment by Almad** [comment]
I have nothing against Python 3, but the thought process was black-belt being used as global command without virtualenv and possibly by non-engineers as well, therefore relying on default mac os x python (currently 2.7.10).

And given I maintain python package that's in Python X (usable 2/3 subset), I opted not to do so.

PRs welcome :P

**Comment by w-vi** [comment]
I can live with virtualenv, was just asking ....

**Comment by w-vi** [comment]
#116 created to make sure nobody asks again :)

**Comment by honzajavorek** [comment]
Not to be just trolling, I'll make couple of notes:

> black-belt being used as global command without virtualenv

That's IMHO valid point.

> Python X

C'mon, it's not _that_ hard (at least since [this article](http://lucumr.pocoo.org/2013/5/21/porting-to-python-3-redux/) and it's 2 years old), especially for something this small. Also, wiriting in Python X from scratch is IMHO much easier than porting to it - you just setup the library well and run tests on both versions.

**Comment by Almad** [comment]
> C'mon, it's not that hard

PRs welcome.

**Comment by honzajavorek** [comment]
I'm re-opening this, as I think we should migrate this tool to Python 3, maybe even Python 3 exclusively so we don't have to deal with "Python X".

1. Any developer can easily install it globally on Mac by `brew install python3 && sudo pip3 install black-belt`.
2. Black Belt is so simple software that just dealing with unicode strings & fixing `print` to have parentheses could be actually enough to port it.
3. The world is moving, planet spinning, Python 2.x is just slowly dying legacy language, let's deal with it and forget it ever existed.

Yes, there are no tests to prove it works as it worked before, but who cares since without tests we can't actually prove Black Belt works at all even now until someone actually runs the commands ¯\\\_(ツ)\_/¯

**Comment by Almad** [comment]
Well, my rule of thumb was IsPython3DefaultOnMyOsYet?

This is true neither for my debian testing nor for my mac os x machine ¯\_(ツ)_/¯

Not completely against it, just don't want to handle it and want to get upgrade guides :)

**Comment by w-vi** [comment]
All my boxes have Python 3 as default, Python 2  will die eventually better to get over it sooner then later is my mantra

**Comment by honzajavorek** [comment]
@Almad It's default on many systems already, but I don't think it's important. AFAIK the issue was ease of installation for end users and those, I think, do not care much whether it's `brew x && pip3 y` or `brew xyz` much. As far as it's simple and always working oneliner, people are okay with it.

> just don't want to handle it

Yup, the issue is there for contributions, not for you to deal with it. I didn't expect that :D

> not dealing with python x

That's why I suggested to just break compatibility and write it in Py3 only. Since probably nobody else than Apiary uses BB, it's just about one e-mail saying "Please uninstall bb and run this command to get it's latest version".

**Comment by Almad** [comment]
:+1: go ahead ;)

**Comment by honzajavorek** [comment]
@w-vi Yup, I didn't really wished to resurrect this, but since Py2 gets more and more obsolete, I thought about how eagerly we jump on newest versions of Node/Babel etc. and thought about "how hard can it be to port bb to py3"?

**Comment by Almad** [comment]
we've decided and let's move one, but FTR let me say that I see a big difference in how to handle dependencies when distributing software vs. running in an environment you own

**Comment by honzajavorek** [comment]
Yup. I'd be far more hesitant and cautious if BB had larger userbase. But I feel it's actually closer to the "environment you own" end in this special case.

**Comment by kylef** [comment]
To be honest, supporting both Python 2 and Python 3 in one code-base is usually very simple and easy to maintain. I'd suggest we support both Python 2 and Python 3 for a little while (until OS X adopts Python 3).

**Comment by Almad** [comment]
> To be honest, supporting both Python 2 and Python 3 in one code-base is usually very simple and easy to maintain.

@kylef do I have a [Paver](https://github.com/paver/paver) maintainer volunteer? :trollface:

**Comment by kylef** [comment]
@Almad Not sure I follow, Paver already supports Python 2 and Python 3? https://github.com/paver/paver/blob/master/.travis.yml#L3-L8

**Comment by Almad** [comment]
@kylef yes, and for me it's PITA to maintain :P
