### ISSUE TITLE
`bb production` doesn't wait for ssh key passphrase input

### ISSUE THREAD

**Issue by dariagrudzien** [apiaryio/black-belt#156]
When using GitHub SSH key with a passphrase, `bb production` spawns the processes and does not wait for the passphrase to be provided for each process. It only gives a chance to enter the passphrase once, so the other processes never end and the task gets stuck.

```
$ bb production
Running `grunt create-slug` with PID 49895
Running `grunt create-slug --app=apiary-staging-pre` with PID 49896
Running `grunt create-slug --app=apiary-staging-qa` with PID 49897


Enter passphrase for key '/Users/dariagrudzien/.ssh/id_rsa': Enter passphrase for key '/Users/dariagrudzien/.ssh/id_rsa': Enter passphrase for key '/Users/dariagrudzien/.ssh/id_rsa':
Everything up-to-date
Grunt task for apiary completed successfully.

^C

Aborted!
```

**Comment by abtris** [comment]
easy fix: use ssh-agent - https://www.ssh.com/ssh/agent

**Comment by Almad** [comment]
Never considered non-agent use-case until my agent broke :trollface: 

Still not sure how to do that well though.

**Comment by abtris** [comment]
I will reword issue that is problem with any input not just ssh. My git `pre-push` hooks fail too.

**Comment by kylef** [comment]
This is a tricky problem to resolve properly. The problem here is there are three separate processes running, how should stdin be forwarded? It can't be forwarded to all three processes, they could have different timings thus repeating same stdin to all will have undesired effects.

#### Password prompt problem

Perhaps it makes sense to design the deployment command to prevent any invoked commands from wanting to have stdin.

The ssh-key problem could be worked around in black-belt itself, black-belt can detect the lack of `SSH_AUTH_SOCK` environment variable and that the user has an ssh-key. In that case black-belt can invoke ssh-agent to create an agent for the session, black-belt can add the ssh-keys and allow user to enter the password a single time via stdin/stdout forwarding. Afterwards simply set the auth socket that ssh-agent returned to the environment as `SSH_AUTH_SOCK`. At the end of the deploy, kill the ssh-agent process.

#### Unknown Hosts

As for @honzajavorek problem, this would be because `heroku.com` is not found in `~/.ssh/known_hosts` so he is promoted to validate the fingerprint. This will happen for ever person when they deploy for the first time on a new machine which doesn't know about the host.

We could simply check if an entry for `heroku.com` is found in known_hosts and add it (perhaps prompt first because I'd hate if black-belt messed with my configs without me knowing).

```shell
$ cat ~/.ssh/known_hosts | grep '^heroku.com,'
heroku.com,50.19.85.132 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAu8erSx6jh+8ztsfHwkNeFr/SZaSOcvoa8AyMpaerGIPZDB2TKNgNkMSYTLYGDK2ivsqXopo2W7dpQRBIVF80q9mNXy5tbt1WE04gbOBB26Wn2hF4bk3Tu+BNMFbvMjPbkVlC2hcFuQJdH4T2i/dtauyTpJbD/6ExHR9XYVhdhdMs0JsjP/Q5FNoWh2ff9YbZVpDQSTPvusUp4liLjPfa/i0t+2LpNCeWy8Y+V9gUlDWiyYwrfMVI0UwNCZZKHs1Unpc11/4HLitQRtvuk0Ot5qwwBxbmtvCDKZvj1aFBid71/mYdGRPYZMIxq1zgP1acePC1zfTG/lvuQ7d0Pe0kaw==
```

---

Note, also that heroku.com by default uses https deploys instead of ssh. Why don't we always deploy with https instead?

This prevents the user having to configure an ssh key to deploy, or hitting any of the above problems. The requirement is that the user has used `heroku login` on the system which I believe is already be required by `grunt` commands.

For orgs using SSO with Heroku, they are forced to use https since ssh deploy is not supported for SSO. Could this be us in the near future?

**Comment by abtris** [comment]
Migrated to apiaryio/bb#24
